CREATE DATABASE PruebaTecnicaDB
USE PruebaTecnicaDB

CREATE TABLE Users (
Id INT PRIMARY KEY IDENTITY (1,1),
FullName NVARCHAR(100) NOT NULL,
Email NVARCHAR(255) NOT NULL UNIQUE,
Pass NVARCHAR(255) NOT NULL,
URole INT NOT NULL
);

CREATE TABLE SeekerProfiles(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	Age NVARCHAR(2) NOT NULL,
	ContactNumber NVARCHAR(15) NOT NULL,
	ELevel INT NOT NULL,
	WorkXP NVARCHAR(MAX) NOT NULL,
	Notes NVARCHAR(MAX) NOT NULL
);

CREATE TABLE EmployerProfiles (
	Id INT PRIMARY KEY IDENTITY(1,1),
	EmployerId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	Location NVARCHAR(255) NOT NULL,
	Industry NVARCHAR(255) NOT NULL,
	EmployeeCount INT DEFAULT 0
);

CREATE TABLE JobOffers (
	Id INT PRIMARY KEY IDENTITY (1,1),
	EmployerId INT NOT NULL FOREIGN KEY REFERENCES SeekerProfiles(Id),
	Title NVARCHAR(200) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	CreatedDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE JobApplications (
	Id INT PRIMARY KEY IDENTITY(1,1),
	SeekerId INT NOT NULL FOREIGN KEY REFERENCES SeekerProfiles(Id),
	JobOfferId INT NOT NULL FOREIGN KEY REFERENCES JobOffers(Id),
	Status INT NOT NULL DEFAULT 0,
	AppliedAt DATETIME DEFAULT GETDATE()
);